version: '3'
services:
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - ./stripe-data:/data/db
    networks:
      - stripe-test
  app: 
    build: .
    command: npm run dev
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
    container_name: stripe-test
    restart: always
    links:
      - mongo
    environment:
      WAIT_HOSTS: mongodb:27017
    networks:
      - stripe-test

networks:
  stripe-test:
    driver: bridge